name: Python Code Formatting Checks

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install -U pip poetry
          poetry install --all-extras --with dev
      - name: Run isort check
        working-directory: python
        run: |
          poetry run isort . --check --diff
      - name: Run black check
        working-directory: python
        run: |
          poetry run black . --check --diff
