name: Python Code Formatting Checks

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        working-directory: python
        env: { UV_SYSTEM_PYTHON: true }
        run: |
          pip install uv
          uv pip install .[all] isort black
      - name: Run isort check
        working-directory: python
        run: |
          isort . --check --diff
      - name: Run black check
        working-directory: python
        run: |
          black . --check --diff
